services:
  - type: web
    name: verbum7-claude-api
    env: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false